Interpreter v0.1
m0rphed/LongArithm pull request #2
Opened 2021-11-01 21:16 UTC by m0rphed

Реализовал простой парсер (исп. `FParsec`) и интерпретатор поддерживающий _pseudo-code-like_ синтаксис, реализовал конструкции: `while`, `if`, `print`, операторы сравнения и переменые.

**example**:
```nim
i = -1
while (i > -10) {
    print (i)
    i = i - 1
}

print (i)
```
**output**:
```
-1
-2
-3
-4
-5
-6
-7
-8
-9
-10
-11
```

2021-11-01 21:19 UTC, m0rphed commented
@gsvgit Примите пожалуйста :pray: а то мой коллега не может делать дальше задания :smirk:

2021-11-01 21:25 UTC, IvanMoskalenko requested changes
Очень неплохо, но кое-что надо поправить

2021-11-01 21:31 UTC, IvanMoskalenko commented on src/LongArithm/MyString.fs
> +module LongArithm.MyString
Кажется, что это лишнее

2021-11-01 21:34 UTC, IvanMoskalenko commented on src/LongArithm.Cli/Program.fs
> +// BigInt on List -- tests
Лишний комментарий.

2021-11-01 21:34 UTC, IvanMoskalenko commented on src/LongArithm.Cli/Program.fs
> +    let parser = ArgumentParser.Create<CLIArguments>(programName = "RegExp interpreter")
Эм... точно RegExp?

2021-11-01 23:40 UTC, m0rphed commented
@IvanMoskalenko, исправил вышеупомянутые недочёты, думаю требуется дополнительное ревью от преподавателя

2021-11-02 08:45 UTC, gsvgit commented on src/LongArithm/BigInt.fs
> +    let systemBigIntToMyList (number: System.Numerics.BigInteger) =
А знак здесь не учитывается? 
А почему не сразу в число, а сперва в MyList? Для MyList просто место странное. Да и вряд ли нужен именно лист сам по себе.

2021-11-02 08:45 UTC, gsvgit commented on src/LongArithm/BigInt.fs
> +    let negate (x: MyBigInt) =
А ```negateSign``` не спасает?

2021-11-02 08:45 UTC, gsvgit commented on src/LongArithm/BigInt.fs
> +    let greater (a: MyBigInt) (b: MyBigInt) =
А почему не сделать относительно типичный compare вместо пачки функций? Пусть он даже будет F#-овый и возвращает DU с тремя значениям.

2021-11-02 08:45 UTC, gsvgit commented on src/LongArithm/Expressions.fs
> +        | _         -> true
Круть. То есть всякая ерунда всегда true ?

2021-11-02 08:45 UTC, gsvgit commented on src/LongArithm/Expressions.fs
> +        | _     -> BigInt.big0
И всё же. Почему, как и с булами, это не ошибка?

2021-11-02 08:45 UTC, gsvgit commented on src/notes/fparsec_arithm.fsx
> +[<AutoOpen>]
А для чего жтот файл? Он просто дублирует парсер.

2021-11-02 09:22 UTC, m0rphed commented on src/notes/fparsec_arithm.fsx
> +[<AutoOpen>]
Это были заметки :memo:, пожалуй удалить нужно

2022-02-25 19:55 UTC, merged